#!/bin/sh -e

# Copyright 2015-2016 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Script to simplify debugging with SortChecker.

gdb \
  -ex "set environment LD_PRELOAD ${LD_PRELOAD:+$LD_PRELOAD:}$(dirname $0)/../bin/libsortcheck.so" \
  -ex 'set pagination off' \
  -ex 'break report_error' \
  -ex 'set print pretty on' \
  -ex run \
  --args "$@"

