#!/bin/sh -e

# Copyright 2015-2016 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

if test $# = 0; then
  cat <<EOF
$(basename $0) [OPTS] "CMDS"
Simple script for running CMDS under SortChecker (with options OPTS).

Example:
  $ sortcheck/scripts/sortcheck print_to_syslog=1 'make clean && make -j2'
EOF
  exit
fi

if ! test -x "$1" && echo "$1" | grep -q =; then
  export SORTCHECK_OPTIONS="$1"
  shift
fi

CMD="$@"

LIB=$(dirname $0)/../lib/libsortcheck.so
if ! test -f $LIB; then
  LIB=$(dirname $0)/../bin/libsortcheck.so
fi

bash -c "export LD_PRELOAD=${LD_PRELOAD:+$LD_PRELOAD:}$LIB; $CMD"
